#+Title: Architecture Tactics Assignment
#+INCLUDE: "./org/header.org-in" org

* About This Sprint
  In this sprint you identify architecture tactics for the most relevant quality attributes for your system.
* User Stories covered in this Sprint
  - As a software architect I want to start my design with a well known structure so that I can be sure that I am addressing my quality requirements in the best way.
* Learning Material
Please revise the sprints on
- [[./Intro-Architectures.org][Introduction to Software Architectures]]
- [[./Architecture-Patterns.org][Software Architecture Patterns]]
- [[./A-Quality-Attributes.org][Quality Attribute Scenarios Assignment]]
* Experiential Learning
** Assignment: Architecture Tactics
    Explore architectural solutions (in terms of architecture tactics) for your quality attribute scenarios.

    {{{tasks}}}
    - For each quality attribute scenario, identify which architectural tactics (from Bass et al.) that might help you achieve the desired response measure.
    - Explore how you would design the architecture of your system to make use of the identified tactics.
    - Also consider what support you would need on the design level (in terms of classes and interactions between classes).
#+BEGIN_info
{{{DocStructure}}}

{{{assignment(Software Architecture and Architecture Tactics)}}}
#+INCLUDE: "./DocStruct.org" org

3. [@3] Architecture Tactics
   1. Tactics for Quality Attribute Scenario 1: <quality attribute name>

      For each scenario:
      - List and describe the tactics that may be relevant.
      - Briefly discuss how you would use the tactic (or why you decide /not/ to use this particular tactic).
      - Identify key components and classes in your design that are affected by applying your selected tactics.

   2. Tactics for Quality Attribute Scenario 2: <quality attribute name>
   3. Tactics for Quality Attribute Scenario 3: <quality attribute name>
   4. Tactics for Quality Attribute Scenario 4: <quality attribute name>
   5. Tactics for Quality Attribute Scenario 5: <quality attribute name>

4. Updated Architecture

   Present an updated architecture (with as many views that are necessary) that includes the tactics you decided to use. Try to mark, in your architecture, which entities are involved in each tactic, and the responsibilities the entity have in relation to the tactic.
#+END_info

{{{commit}}}

#+BEGIN_tip
{{{condSat}}}

When marking this part of the assignment we are looking for the following:

0. [@0] Does the title page contain a table with authors and author contribution?
1. Size of assignment: Are two to three tactics explored for each of the five quality attribute scenarios?
2. Will the discussed tactics address the challenges in each quality attribute scenario?
3. Are the tactics adequately translated into a workable architecture and design for the particular system?
4. Does the updated architecture have a reasonable potential to address the quality attribute scenarios?
#+END_tip

* Sprint Acceptance Tests
  You are done with this sprint when:
  - You have explored architecture tactics that address your quality attribute scenarios.
  - You have updated your software architecture according to the tactics.
  - You have committed/pushed these documents to your project repository.


  You may also have
  - Updated your Sprint Test Plan
  - Updated your Course Backlog   
