#+Title: Quality Attribute Scenarios Assignment
#+INCLUDE: "./org/header.org-in" org

* About This Sprint
  In this sprint you identify the most relevant quality attributes for your system and describe them as quality attribute scenarios.
* User Stories covered in this Sprint
  - As a software architect I want to start my design with a well known structure so that I can be sure that I am addressing my quality requirements in the best way.
* Learning Material
Please revise the sprints on
- [[./Intro-Architectures.org][Introduction to Software Architectures]]
- [[./Architecture-Patterns.org][Software Architecture Patterns]]
* Experiential Learning
** Assignment: Quality Attribute Scenarios
    List, briefly describe, and prioritise the most important quality attributes that you need to consider in your system. Develop quality attribute scenarios for the most important ones.

    {{{tasks}}}
    - Identify the most important quality attributes for your system.
    - Briefly describe each of them so that it is possible to understand what the quality attribute means in the context of your system and why it is imporant.
    - Prioritise your quality attributes so you know which are the most important for your system.
    - Develop /Quality Attribute Scenarios/ for the top five most important quality attributes.

#+BEGIN_info
{{{DocStructure}}}

{{{assignment(Quality Attribute Scenarios)}}}
#+INCLUDE: "./DocStruct.org" org

3. [@3] Prioritised list of Quality Attributes

   List your quality attributes in order of priority and briefly describe them.
4. Quality Attribute Scenarios

   Your five most important quality attributes, expressed as quality attribute scenarios. This may be expressed as figures, but it is more useful if you present them in a table:

   | Aspect           | Value |
   |------------------+-------|
   | Source           |       |
   | Stimulus         |       |
   | Artifact         |       |
   | Environment      |       |
   | Response         |       |
   | Response Measure |       |

   *Note:* You also need to explain your values with one or two sentences for each aspect.
#+END_info

{{{commit}}}

#+BEGIN_tip
{{{condSat}}}

When marking this part of the assignment we are looking for the following:

0. [@0] Does the title page contain a table with authors and author contribution?
1. Size of assignment: Are there more than five quality attributes listed?
2. Size of assignment: Are there five quality attribute scenarios?
3. Do the prioritisation of the quality attributes make sense with respect to the system?
4. For each scenario: Are appropriate sources, stimuli, and artifacts listed?
5. For each scenario: Is the environment reasonable?
6. For each scenario: Is the response appropriate given the stimulus?
7. For each scenario: Is the response measure reasonable given the type of response, the stimulus, and the environment?
#+END_tip
* Sprint Acceptance Tests
  You are done with this sprint when:
  - You have created quality attribute scenarios for your most important quality attributes.
  - You have committed/pushed these documents to your project repository.


  You may also have
  - Updated your Sprint Test Plan
  - Updated your Course Backlog   
