#+Title: Requirements Engineering Assignment
#+INCLUDE: "./org/header.org-in" org


* About This Sprint
   This sprint briefly introduces the topic requirements engineering.
* User Stories covered in this Sprint
  - As a requirements engineer I want to know who may have requirements on the system we are building so that I can make sure that all needs are met.
  - As a requirements engineer I want to have a range of methods for finding requirements so that I can choose the best method for each person or source of requirements.
  - As a requirements engineer I want to document the found requirements so that I can discuss them with the customer.
  - As a requirements engineer I want to document the found requirements so that I can communicate them to the developers.
  - As a project manager I need to decide what to focus on building right now so that I best satisfy all customers' expectations.
  - As a teacher I want to evaluate the students' ability to express requirements as user stories for a system so that I know they understand modern requirements engineering elicitation and specification practices.
* Learning Material
  Please review the sprints concerning
  - [[./Requirements-Engineering.org][Requirements Engineering]]
* Experiential Learning
** Assignment: Requirements Document
    Your main task is to write user stories based on the system description for the assignments.

    *Tasks*
    1. Describe the system in terms of the most important workflows, as "epics". Add conditions of satisfaction to each epic.
    2. List the epics in order of importance, and add a brief motivation for why you have ordered them the way you have.
    3. Take the three most important epics, and break them down to more manageable user stories. Add conditions of satisfaction to the user stories. Order them according to priority, and add a brief motivation.

#+BEGIN_info
{{{DocStructure}}}

{{{assignment(User Stories)}}}
#+INCLUDE: "./DocStruct.org" org

3. [@3] Epics
   1. Motivation for Priority
   2. Epics (ordered most important first)
4. User Stories and Epics
   1. Motivation for Priority
   2. User Stories and Epics (ordered most important first)
#+END_info    

#+BEGIN_note
*Please note* that the "User Stories and Epics" shall include /both/ the remaining epics from section 3 in the document /and/ the broken down user stories.

*Please also note* that the user stories from the epics that you break down will probably be interlaced; the least important user stories from the top-most epic need not be more important than the most important user stories from the second epic. You will thus have to review the priorities of /all/ user stories against all other user stories and epics.

*Please also also note*, when you go forward you will want each user story to have a unique ID so that you can refer back to them.
#+END_note

{{{commit}}}

#+BEGIN_tip
{{{condSat}}}

When marking this part of the assignment we are looking for the following:

0. [@0] Does the title page contain a table with authors and author contribution 
1. Size of assignment: Are there 5-10 epics and 10-30 user stories?
2. Is there a significant difference in scope between the epics and the user stories?
3. Are the epics and user stories well formed (including actor, goal, and reason)?
4. Are there relevant conditions of satisfaction for each user story/epic?
5. Is there a reasonable motivation for the priorities of the epics and user stories?
6. Does the prioritisation actually follow the motivation?
#+END_tip

* Sprint Acceptance Tests
  You are done with this sprint when:
  - You have created the "User Stories" document and committed/pushed it to your project repository.

  You may also have
  - Updated your Sprint Test Plan
  - Updated your Course Backlog
